FROM golang:1.25-alpine

WORKDIR /app

# Устанавливаем reflex для hot reload
RUN go install github.com/cespare/reflex@latest

# Копируем файлы модулей
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Открываем порт
EXPOSE 8080

# Запускаем с hot reload и передаем переменные
CMD ["reflex", "-g", "**/*.go", "-s", "--", "go", "run", "./cmd/server"]