version: '3.8'

services:
  app:
    image: my-app:prod
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env.prod
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    restart: always

volumes:
  postgres-data: